---
- name: Install "cordova" package globally.
  npm:
    name: cordova@8
    global: true
  environment:
    PATH: "/Users/{{ work_user }}/.nvm/versions/node/{{ node_version }}/bin/"

- name: Build sdkmanager
  shell: >
    set -o pipefail echo -ne 'y\n' | PATH="$PATH:/usr/local/bin"
    sdkmanager "build-tools;{{ sdk_buildtools_version }}"
  changed_when: false

- name: Install cocoapods
  become: true
  become_method: sudo
  command: gem install cocoapods
  changed_when: false
