---
- name: Install "cordova" package globally.
  npm:
    name: cordova@8
    global: true
  environment:
    PATH: "{{ lookup('env','PATH') }}"

- name: Build sdkmanager
  shell: |
    set -o pipefail
    echo -ne 'y\n' | PATH="$PATH:/usr/local/bin" sdkmanager "build-tools;{{ sdk_buildtools_version }}"
  changed_when: false

- name: Install cocoapods
  become: true
  become_method: sudo
  command: gem install cocoapods
  changed_when: false

- name: Copy info file
  become: true
  template: src=info.txt.j2 dest=/Users/{{ work_user }}/Desktop/mobile_software.txt
