---
- name: Install "cordova" package globally.
  npm:
    name: cordova@8
    global: true
  environment:
    PATH: "{{ lookup('env','PATH') }}"

- name: Check node versions
  shell: . $HOME/.zshrc && node -v
  args:
    executable: /bin/zsh
  register: node_v

- name: Set node versions to fact
  set_fact:
    nvm_node_version: "{{ node_v.stdout }}"

- name: Create a symbolic link to cordova
  file:
    src: $HOME/.nvm/versions/node/{{ nvm_node_version }}/bin/cordova
    dest: /usr/local/bin/cordova
    state: link

- name: Build sdkmanager
  shell: |
    set -o pipefail
    echo -ne 'y\n' | PATH="$PATH:/usr/local/bin" sdkmanager "build-tools;{{ sdk_buildtools_version }}"
  changed_when: false

- name: Install cocoapods
  become: true
  become_method: sudo
  gem:
    name: cocoapods
    version: {{ cocoapods_version }}
    state: present

- name: Copy info file
  template: src=info.txt.j2 dest=$HOME/Desktop/mobile_software.txt
