---
- name: Install "cordova" package globally.
  npm:
    name: cordova@8
    global: true
  environment:
    PATH: "{{ lookup('env','PATH') }}"

- name: Check node versions
  shell: . $HOME/.zshrc && node -v
  args:
    executable: /bin/zsh
  register: node_v
  changed_when: false

- name: Set node versions to fact
  set_fact:
    nvm_node_version: "{{ node_v.stdout }}"

- name: Create a symbolic link to cordova
  file:
    src: $HOME/.nvm/versions/node/{{ nvm_node_version }}/bin/cordova
    dest: /usr/local/bin/cordova
    state: link
    mode: 0777

- name: Build sdkmanager
  shell: |
    set -o pipefail
    echo -ne 'y\n' |
    PATH="$PATH:/usr/local/bin" sdkmanager "{{ sdk_buildtools_version }}"
  changed_when: false

- name: Set export vars for ruby
  blockinfile:
    path: ~/.zshrc
    block: |
      export PATH="/usr/local/opt/ruby/bin:$PATH"
      export LDFLAGS="-L/usr/local/opt/ruby/lib"
      export CPPFLAGS="-I/usr/local/opt/ruby/include"
      export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

- name: Source zshrc
  become: false
  command: /bin/zsh -c "source ~/.zshrc"
  changed_when: false

- name: Set home_dir to fact
  set_fact:
    user_home_dir: "{{ ansible_env.HOME }}"

- name: Install cocoapods
  become: true
  become_method: sudo
  shell: . "{{ user_home_dir }}"/.zshrc
    && gem install -n /usr/local/bin cocoapods
  args:
    executable: /bin/zsh
  changed_when: false

- name: Copy info file
  template:
    src: info.txt.j2
    dest: $HOME/Desktop/mobile_software.txt
    mode: 0777
  changed_when: false
