---
- name: Download jdk.dmg
  get_url:
    url: "{{ java_url }}"
    dest: /tmp

- name: Mount the downloaded dmg
  command: hdiutil attach -mountpoint /Volumes/jdk /tmp/{{ java_name }}.dmg
  changed_when: false

- name: Install the pkg file from the dmg
  become: true
  become_method: sudo
  command: installer -package /Volumes/jdk/JDK\ {{ java_version }}\ Update\ {{ java_release }}.pkg -target /
  changed_when: false

- name: Unmount the downloaded dmg
  command: hdiutil detach /Volumes/jdk
  changed_when: false
